# An example of ClusterConfig object using an existing VPC:
# You can find more examples in https://github.com/eksctl-io/eksctl/tree/main/examples
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.33"

vpc:
  id: "vpc-02fb780c7f09b80a3"
  subnets:
    public:
      us-east-1b:
          id: "subnet-0c35c7fcaecb9f54d"
      us-east-1c:
          id: "subnet-0335f6005ebeb7b48"

iam:
  withOIDC: true

managedNodeGroups:
- name: cloud-eks-workers
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
  instanceTypes: ["t2.small","t3.large"]
  spot: true

cloudWatch:
    clusterLogging:
        enableTypes: ["audit", "authenticator", "controllerManager"]
